export const countryCodeMap: Record<string, string> = {
  Afghanistan: "AF",
  Albania: "AL",
  Algeria: "DZ",
  Andorra: "AD",
  "Antigua and Barbuda": "AG",
  Angola: "AO",
  Argentina: "AR",
  Armenia: "AM",
  Aruba: "AW",
  Australia: "AU",
  Austria: "AT",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Barbados: "BB",
  Belarus: "BY",
  Belgium: "BE",
  Belize: "BZ",
  Benin: "BJ",
  Bermuda: "BM",
  Bhutan: "BT",
  Bolivia: "BO",
  "Bosnia and Herzegovina": "BA",
  "British Virgin Islands": "VG",
  Botswana: "BW",
  Brazil: "BR",
  Brunei: "BN",
  Bulgaria: "BG",
  "Burkina Faso": "BF",
  Burundi: "BI",
  "Cabo Verde": "CV",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  "Central African Republic": "CF",
  Chad: "TD",
  Chile: "CL",
  China: "CN",
  Colombia: "CO",
  Comoros: "KM",
  "Costa Rica": "CR",
  "Côte d'Ivoire": "CI",
  Croatia: "HR",
  Cyprus: "CY",
  "Czech Republic": "CZ",
  "Democratic Republic of the Congo": "CD",
  Denmark: "DK",
  Djibouti: "DJ",
  Dominica: "DM",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  Estonia: "EE",
  Eswatini: "SZ",
  Ethiopia: "ET",
  Fiji: "FJ",
  "Falkland Islands": "FK",
  Finland: "FI",
  France: "FR",
  Gabon: "GA",
  Gambia: "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Gibraltar: "GI",
  Greece: "GR",
  Greenland: "GL",
  Grenada: "GD",
  Guatemala: "GT",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Guyana: "GY",
  "Hong Kong": "HK",
  Hungary: "HU",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Haiti: "HT",
  Honduras: "HN",
  Iraq: "IQ",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jordan: "JO",
  Kazakhstan: "KZ",
  Kenya: "KE",
  Kosovo: "XK",
  Kuwait: "KW",
  Kyrgyzstan: "KG",
  Laos: "LA",
  Latvia: "LV",
  Lebanon: "LB",
  Lesotho: "LS",
  Liberia: "LR",
  Libya: "LY",
  Liechtenstein: "LI",
  Lithuania: "LT",
  Luxembourg: "LU",
  Macedonia: "MK",
  Madagascar: "MG",
  Malawi: "MW",
  Malaysia: "MY",
  Maldives: "MV",
  Mali: "ML",
  Malta: "MT",
  Mauritania: "MR",
  Mauritius: "MU",
  Mexico: "MX",
  Moldova: "MD",
  Monaco: "MC",
  Mongolia: "MN",
  Montenegro: "ME",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Nepal: "NP",
  Netherlands: "NL",
  "New Jersey": "NJ",
  "New Zealand": "NZ",
  Niger: "NE",
  Nicaragua: "NI",
  Nigeria: "NG",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Panama: "PA",
  Palau: "PW",
  Paraguay: "PY",
  "Papua New Guinea": "PG",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Qatar: "QA",
  "Republic of the Congo": "CG",
  Romania: "RO",
  Russia: "RU",
  Rwanda: "RW",
  Samoa: "WS",
  "San Marino": "SM",
  "São Tomé and Príncipe": "ST",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Serbia: "RS",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  "Solomon Islands": "SB",
  Singapore: "SG",
  Slovakia: "SK",
  Slovenia: "SI",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  "South Sudan": "SS",
  Spain: "ES",
  "Sri Lanka": "LK",
  Sudan: "SD",
  Suriname: "SR",
  Sweden: "SE",
  Switzerland: "CH",
  Taiwan: "TW",
  Tajikistan: "TJ",
  Tanzania: "TZ",
  Thailand: "TH",
  "Timor-Leste": "TL",
  "Trinidad and Tobago": "TT",
  Tonga: "TO",
  Togo: "TG",
  "Turks and Caicos Islands": "TC",
  Tunisia: "TN",
  Turkey: "TR",
  Turkmenistan: "TM",
  Uganda: "UG",
  UK: "GB",
  Ukraine: "UA",
  "United Arab Emirates": "AE",
  "United States": "US",
  Uruguay: "UY",
  Uzbekistan: "UZ",
  Venezuela: "VE",
  Vanuatu: "VU",
  "Vatican City": "VA",
  Vietnam: "VN",
  Yemen: "YE",
  Zambia: "ZM",
  Zimbabwe: "ZW",
};

// Helper function to get country name from country code
export function getCountryNameFromCode(countryCode: string): string {
  const entry = Object.entries(countryCodeMap).find(
    ([_, code]) => code === countryCode
  );
  if (entry) {
    return entry[0];
  }

  // Intelligent fallback based on region
  const regionFallbacks: Record<string, string> = {
    // Asia-Pacific
    AS: "China",
    AP: "China",
    CN: "China",
    JP: "Japan",
    KR: "South Korea",
    IN: "India",
    SG: "Singapore",
    TH: "Thailand",
    MY: "Malaysia",
    ID: "Indonesia",
    PH: "Philippines",
    VN: "Vietnam",
    BD: "Bangladesh",
    PK: "Pakistan",
    LK: "Sri Lanka",
    MM: "Myanmar",
    KH: "Cambodia",
    LA: "Laos",
    MN: "Mongolia",
    NP: "Nepal",
    BT: "Bhutan",

    // Europe
    EU: "Germany",
    DE: "Germany",
    FR: "France",
    GB: "United Kingdom",
    IT: "Italy",
    ES: "Spain",
    NL: "Netherlands",
    SE: "Sweden",
    NO: "Norway",
    DK: "Denmark",
    FI: "Finland",
    CH: "Switzerland",
    AT: "Austria",
    BE: "Belgium",
    PL: "Poland",
    CZ: "Czech Republic",
    HU: "Hungary",
    RO: "Romania",
    BG: "Bulgaria",
    HR: "Croatia",
    SI: "Slovenia",
    SK: "Slovakia",
    EE: "Estonia",
    LV: "Latvia",
    LT: "Lithuania",
    IE: "Ireland",
    PT: "Portugal",
    GR: "Greece",

    // Americas
    NA: "United States",
    US: "United States",
    CA: "Canada",
    MX: "Mexico",
    BR: "Brazil",
    AR: "Argentina",
    CL: "Chile",
    CO: "Colombia",
    PE: "Peru",
    VE: "Venezuela",
    UY: "Uruguay",
    PY: "Paraguay",
    BO: "Bolivia",
    EC: "Ecuador",
    GY: "Guyana",
    SR: "Suriname",

    // Africa
    AF: "South Africa",
    ZA: "South Africa",
    NG: "Nigeria",
    EG: "Egypt",
    KE: "Kenya",
    GH: "Ghana",
    MA: "Morocco",
    TN: "Tunisia",
    DZ: "Algeria",
    LY: "Libya",
    SD: "Sudan",
    ET: "Ethiopia",
    UG: "Uganda",
    TZ: "Tanzania",
    RW: "Rwanda",
    MW: "Malawi",
    ZM: "Zambia",
    ZW: "Zimbabwe",
    BW: "Botswana",
    NA_AF: "Namibia",

    // Middle East
    ME: "Saudi Arabia",
    SA: "Saudi Arabia",
    AE: "United Arab Emirates",
    QA: "Qatar",
    KW: "Kuwait",
    BH: "Bahrain",
    OM: "Oman",
    JO: "Jordan",
    LB: "Lebanon",
    SY: "Syria",
    IQ: "Iraq",
    IR: "Iran",
    TR: "Turkey",
    IL: "Israel",
    PS: "Palestine",

    // Oceania
    OC: "Australia",
    AU: "Australia",
    NZ: "New Zealand",
    FJ: "Fiji",
    PG: "Papua New Guinea",
    SB: "Solomon Islands",
    VU: "Vanuatu",
    TO: "Tonga",
    WS: "Samoa",
    KI: "Kiribati",
    TV: "Tuvalu",
  };

  // Try to find a regional fallback
  const regionFallback = regionFallbacks[countryCode];
  if (regionFallback) {
    return regionFallback;
  }

  // Final fallback based on common patterns
  if (countryCode.startsWith("A")) return "Australia";
  if (countryCode.startsWith("B")) return "Brazil";
  if (countryCode.startsWith("C")) return "Canada";
  if (countryCode.startsWith("D")) return "Germany";
  if (countryCode.startsWith("E")) return "Spain";
  if (countryCode.startsWith("F")) return "France";
  if (countryCode.startsWith("G")) return "Germany";
  if (countryCode.startsWith("H")) return "Hungary";
  if (countryCode.startsWith("I")) return "Italy";
  if (countryCode.startsWith("J")) return "Japan";
  if (countryCode.startsWith("K")) return "South Korea";
  if (countryCode.startsWith("L")) return "Luxembourg";
  if (countryCode.startsWith("M")) return "Mexico";
  if (countryCode.startsWith("N")) return "Netherlands";
  if (countryCode.startsWith("O")) return "Oman";
  if (countryCode.startsWith("P")) return "Poland";
  if (countryCode.startsWith("Q")) return "Qatar";
  if (countryCode.startsWith("R")) return "Russia";
  if (countryCode.startsWith("S")) return "Sweden";
  if (countryCode.startsWith("T")) return "Turkey";
  if (countryCode.startsWith("U")) return "United States";
  if (countryCode.startsWith("V")) return "Venezuela";
  if (countryCode.startsWith("W")) return "United States";
  if (countryCode.startsWith("X")) return "United States";
  if (countryCode.startsWith("Y")) return "Yemen";
  if (countryCode.startsWith("Z")) return "Zimbabwe";

  // Ultimate fallback
  return "United States";
}
